# Generated by Django 3.2.18 on 2024-03-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_our_guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
