# Generated by Django 5.0.2 on 2024-03-25 14:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('loginEnabled', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countriesId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('tableId', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('venueDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('countriesId', models.ForeignKey(db_column='countriesID', on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
            options={
                'db_table': 'VenueDetails',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idevent', models.AutoField(primary_key=True, serialize=False)),
                ('hostID', models.IntegerField(null=True)),
                ('eventType', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('respondByDate', models.DateField(default=datetime.datetime(2024, 4, 24, 14, 4, 14, 840418, tzinfo=datetime.timezone.utc))),
                ('venueDetailsID', models.ForeignKey(db_column='venueDetailsID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.venuedetails')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
