# Generated by Django 5.0.2 on 2024-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('loginEnabled', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idevent', models.AutoField(primary_key=True, serialize=False)),
                ('hostID', models.IntegerField(null=True)),
                ('eventType', models.CharField(max_length=255)),
                ('venueDetailsID', models.IntegerField(null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('tableId', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
