# Generated by Django 3.2.18 on 2024-03-21 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countriesId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='respondByDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 13, 43, 22, 76468, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('venueDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('countriesId', models.ForeignKey(db_column='countriesID', on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
            options={
                'db_table': 'VenueDetails',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='venueDetailsID',
            field=models.ForeignKey(db_column='venueDetailsID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.venuedetails'),
        ),
    ]
