# Generated by Django 3.2.18 on 2024-03-26 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240321_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('reply', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestRsvp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_attending', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='countriesId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='countryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventType',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='idevent',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='venue_time_1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hostID',
        ),
        migrations.RemoveField(
            model_name='event',
            name='respondByDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venueDetailsID',
        ),
        migrations.AddField(
            model_name='event',
            name='respond_by_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue_time_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_time_3',
            field=models.TimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='county',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='County',
        ),
        migrations.DeleteModel(
            name='VenueDetails',
        ),
        migrations.AddField(
            model_name='venue',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.county'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venuetype'),
        ),
        migrations.AddField(
            model_name='table',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue'),
        ),
        migrations.AddField(
            model_name='guestrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AddField(
            model_name='guestrsvp',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestrsvp',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.table'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue_1', to='app.venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_2', to='app.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_3', to='app.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue_details_id', to='app.venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='wedding_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.weddingtype'),
            preserve_default=False,
        ),
    ]
