# Generated by Django 5.0.2 on 2024-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('eventId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
