# Generated by Django 5.0.1 on 2024-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_host_delete_helloworld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guestId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('tableId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
