# Generated by Django 5.0.1 on 2024-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_guest_delete_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='eventId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tableId',
            field=models.IntegerField(null=True),
        ),
    ]
